name: Build and Publish to ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Extract git metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: 058264526568.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/imediato-nautica-chat

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./chat
          push: true
          tags: 058264526568.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/imediato-nautica-chat:latest
        env:
          OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Post build info
        run: |
          echo "Image URL: 058264526568.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/imediato-nautica-chat:latest"
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
