name: Deploy main page to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          if aws --version; then
            echo "AWS CLI already installed, updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create S3 bucket if it doesn't exist
        run: |
          if aws s3api head-bucket --bucket imediatonautica.com.br 2>/dev/null; then
            echo "Bucket exists"
          else
            echo "Bucket does not exist, creating..."
            aws s3api create-bucket --bucket imediatonautica.com.br --region ${{ vars.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ vars.AWS_REGION }}
            aws s3api put-bucket-versioning --bucket imediatonautica.com.br --versioning-configuration Status=Enabled

      - name: Sync files to S3
        run: |
          aws s3 sync ./main s3://imediatonautica.com.br --delete
